initial_position:
  joint_1: 0.0
  joint_2: 0.0
  joint_3: 0.0
  joint_4: 0.0
  joint_5: 0.0
  joint_6: 0.0
  joint_7: 0.0
  joint_8: 0.0
  joint_9: 0.0
  joint_10: 0.0
  joint_11: 0.0
  joint_12: 0.0
  joint_13: 0.0
  joint_14: 0.0
  joint_15: 0.0
  joint_16: 0.0
  joint_17: 0.0
  joint_18: 0.0
  joint_19: 0.0
  joint_20: 0.0
  
