default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_2:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_3:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_4:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_5:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_6:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_7:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_8:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_9:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0
  
  joint_10:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0
  
  joint_11:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_12:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_13:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_14:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_15:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_16:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_17:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_18:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_19:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0

  joint_20:
    has_velocity_limits: true
    max_velocity: 10.0
    max_acceleration_limits: false
    max_acceleration: 0.0